CREATE DATABASE gamezone;

USE gamezone;

CREATE TABLE usuario (
	idUsuario INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(70) NOT NULL,
	email VARCHAR(70) UNIQUE NOT NULL,
	senha VARCHAR(50) NOT NULL,
	nick VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE pontos (
	idPonto INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	maxPontos DECIMAL(2),
    fkUsuario INT, 
    FOREIGN KEY (fkUsuario) REFERENCES usuario(idUsuario)
);